### PR TITLE
std is gone

### PR DESCRIPTION
**Pull request by jwklong**
the script broke so i got rid of the script

### CODE REVIEW

**Comment by jwklong** [comment]
link this to the issue

**Comment by Alpha-404** [comment]
the script works fine wdym also take down your branch since you didn't make anything

**Comment by jwklong** [comment]
> the script works fine wdym also take down your branch since you didn't make anything

i removed the survive the disasters admin panel. also i patched it again so haha YEEEEEEEEEEEEEEEEEEET

**Comment by jwklong** [comment]
yeah its gone

**Pull request closed without merging**
